name: Deploy Static Web

on:
  push:
    branches: [main]
    paths:
      - "web-statis/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image statis
        uses: docker/build-push-action@v5
        with:
          context: ./web-statis
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/uas_statis:latest

      - name: Copy docker-compose ke EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/docker-aws/"

      - name: Deploy ke AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/docker-aws
            docker compose pull container-statis
            docker compose stop container-statis
            docker compose rm -f container-statis
            docker compose up -d container-statis
            echo "[statis] deployed at $(date)"
